# Generated by Django 3.1 on 2020-08-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20200822_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='images/111.png', null=True, upload_to='images/'),
        ),
    ]
