# Generated by Django 3.1 on 2020-08-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20200822_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default=5, upload_to='images/'),
            preserve_default=False,
        ),
    ]
